/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package todosPersonas;

import static CargarEntrenamiento.cargarEntreno.txtnombreEntreno;

import conexionBase.conexionBase;
import entrenamiento.grafica;
import force.miprincipal;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultCellEditor;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import todosPersonas.conexionFederado;

/**
 *
 * @author CarlosEfrain
 */
public class Usuarios extends javax.swing.JInternalFrame {
   
public static int cedula;
public static String nombre, apellido, direccion, telefono,email, fecInicio, fecNacimiento,sexo; 
public static conexionUsuarios obj=new conexionUsuarios();
public static DateFormat fecha = new SimpleDateFormat("yyyy/MM/dd");
public static Date fecha1, fecha2;
public static  String txt_direccion=null;
String convertido ;

public static Validator validar=new Validator();
    /**
     * Creates new form federado
     */
    public Usuarios() {
        initComponents();
        jButton1.requestFocus();
        TXTnombre.setEnabled(false);
        TXTapellido.setEnabled(false);
        TXTtelefono.setEnabled(false);
        TXTdireccion.setEnabled(false);
        TXTemail.setEnabled(false);
        fechaInic.setEnabled(false);
        fecnacimiento.setEnabled(false);
        comboProvincia.setEnabled(false);
        combotipousuario.setEnabled(false);
        LSTsexo.setEnabled(false);
        txtcontraseña1.setEnabled(false);
        txtcontraseña2.setEnabled(false);
        foto_label2.setEnabled(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TXTapellido = new javax.swing.JTextField();
        TXTcedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTdireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXTnombre = new javax.swing.JTextField();
        LSTsexo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        TXTemail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TXTtelefono = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        comboProvincia = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fechaInic = new com.toedter.calendar.JDateChooser();
        fecnacimiento = new com.toedter.calendar.JDateChooser();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        foto_label2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcontraseña2 = new javax.swing.JPasswordField();
        txtcontraseña1 = new javax.swing.JPasswordField();
        combotipousuario = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("USUARIOS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/gym2.png"))); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Apellidos");

        TXTapellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTapellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTapellidoKeyTyped(evt);
            }
        });

        TXTcedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTcedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTcedulaFocusLost(evt);
            }
        });
        TXTcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTcedulaKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombres");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cedula ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Sexo");

        TXTdireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTdireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTdireccionFocusLost(evt);
            }
        });
        TXTdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTdireccionActionPerformed(evt);
            }
        });
        TXTdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTdireccionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTdireccionKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Direccion");

        TXTnombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTnombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTnombreKeyTyped(evt);
            }
        });

        LSTsexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LSTsexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "seleccione sexo", "masculino ", "fememino" }));
        LSTsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LSTsexoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Email");

        TXTemail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTemailFocusLost(evt);
            }
        });
        TXTemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTemailKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Telefono");

        TXTtelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTtelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTtelefonoKeyTyped(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton1FocusLost(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboProvincia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "seleccione Provincia", " Azuay ", "Bolivar ", "Cañar ", "Chimborazo ", "Cotopaxi ", "El Oro ", "Esmeraldas ", "Galápagos ", "Guayas ", "Imbabura ", "Loja ", "Los Rios ", "Manabí ", "Morona Santiago ", "Napo ", "Orellana ", "Pastaza ", "Pichincha", "Santa Elena ", "Santo Domingo de los Tsáchilas ", "Sucumbíos ", "Tungurahua ", "Zamora Chinchipe " }));
        comboProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProvinciaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Provincia");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fec. Nac.");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Fec. Inic.");

        fechaInic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechaInicKeyTyped(evt);
            }
        });

        fecnacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fecnacimientoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fecnacimientoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTemail)
                            .addComponent(TXTtelefono)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(46, 46, 46)
                        .addComponent(LSTsexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TXTcedula))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(27, 27, 27)
                        .addComponent(comboProvincia, 0, 277, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaInic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecnacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTnombre)
                            .addComponent(TXTdireccion)
                            .addComponent(TXTapellido))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(comboProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(fecnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(fechaInic, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TXTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TXTemail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(LSTsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        foto_label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/profile-42914_640.png"))); // NOI18N
        foto_label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foto_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foto_label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foto_label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tipo de usuario ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Contraseña");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Rep. Contraseña");

        txtcontraseña2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcontraseña2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcontraseña2FocusLost(evt);
            }
        });

        txtcontraseña1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcontraseña1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcontraseña1FocusLost(evt);
            }
        });

        combotipousuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combotipousuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione tipo", "NORMAL", "ADMINISTRADOR" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcontraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combotipousuario, 0, 171, Short.MAX_VALUE)
                            .addComponent(txtcontraseña1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combotipousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(txtcontraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcontraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProvinciaActionPerformed
       universales(); // TODO add your handling code here:
    }//GEN-LAST:event_comboProvinciaActionPerformed

    private void LSTsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LSTsexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LSTsexoActionPerformed

    private void foto_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foto_labelMouseClicked
        if (TXTnombre.isEnabled()){
            txt_direccion=null;
        File archivo;
        JFileChooser flcAbrirArchivo = new JFileChooser();
        flcAbrirArchivo.setFileFilter(new FileNameExtensionFilter("Archivo de Imagen", "jpg", "jpeg", "png"));
        int respuesta = flcAbrirArchivo.showOpenDialog(this);

        if (respuesta == JFileChooser.APPROVE_OPTION) {
            archivo = flcAbrirArchivo.getSelectedFile();
            txt_direccion=archivo.getAbsolutePath();
            Image foto = getToolkit().getImage(txt_direccion);
            foto = foto.getScaledInstance(160, 165, 1);
            foto_label2.setIcon(new ImageIcon(foto));
        }
        }
    }//GEN-LAST:event_foto_labelMouseClicked

    private void TXTcedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTcedulaFocusLost
 //JOptionPane.showMessageDialog(null, "error");
        if (!validar.VerificaCedula(TXTcedula.getText())) {
          //  JOptionPane.showMessageDialog(null, "Error al digitar Cedula","Error",JOptionPane.ERROR_MESSAGE);
            }  
        
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTcedulaFocusLost

    private void TXTcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTcedulaKeyTyped
       
        try {
            Double.parseDouble(TXTcedula.getText()+evt.getKeyChar());
            if (validar.VerificaCedula(TXTcedula.getText()+evt.getKeyChar())) {
                     TXTnombre.setEnabled(true);
                    TXTapellido.setEnabled(true);
                    TXTtelefono.setEnabled(true);
                    TXTdireccion.setEnabled(true);
                    TXTemail.setEnabled(true);
                    fechaInic.setEnabled(true);
                    fecnacimiento.setEnabled(true);
                    comboProvincia.setEnabled(true);
                    combotipousuario.setEnabled(true);
                    LSTsexo.setEnabled(true);
                    txtcontraseña1.setEnabled(true);
                    txtcontraseña2.setEnabled(true);
                    foto_label2.setEnabled(true);
            } 
        } catch (Exception e) {
            evt.consume();
        }
          
universales();
    }//GEN-LAST:event_TXTcedulaKeyTyped

    private void TXTdireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTdireccionFocusLost
       
    }//GEN-LAST:event_TXTdireccionFocusLost

    private void TXTemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTemailFocusLost
        if(!checkEmail(TXTemail.getText())){
            JOptionPane.showMessageDialog(null, "Error el email es invalido","Error",JOptionPane.ERROR_MESSAGE);
           
        }
        universales();// TODO add your handling code here:
    }//GEN-LAST:event_TXTemailFocusLost

    private void TXTnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTnombreKeyTyped
try {
            Double.parseDouble(String.valueOf(evt.getKeyChar()));
           evt.consume();
        } catch (Exception e) {
          
        } 
universales();// TODO add your handling code here:
    }//GEN-LAST:event_TXTnombreKeyTyped

    private void TXTapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTapellidoKeyTyped
       try {
            Double.parseDouble(String.valueOf(evt.getKeyChar()));
           evt.consume();
        } catch (Exception e) {
          
        }
       universales();// TODO add your handling code here:
    }//GEN-LAST:event_TXTapellidoKeyTyped

    private void TXTtelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTtelefonoKeyTyped
try {
            Double.parseDouble(String.valueOf(evt.getKeyChar()));
          
        } catch (Exception e) {
           evt.consume();
        } 
universales();// TODO add your handling code here:
    }//GEN-LAST:event_TXTtelefonoKeyTyped

    private void fecnacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fecnacimientoKeyTyped
      // TODO add your handling code here:
    }//GEN-LAST:event_fecnacimientoKeyTyped

    private void fechaInicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaInicKeyTyped
      // TODO add your handling code here:
    }//GEN-LAST:event_fechaInicKeyTyped

    private void txtcontraseña2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontraseña2FocusLost
  universales();      // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraseña2FocusLost

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    miprincipal.planprin=false;
     miprincipal.calendarioprin=false;
     miprincipal.entrenamiento=false;
      miprincipal.usuario=true;
     miprincipal.federado=false;        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void TXTdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTdireccionActionPerformed

    private void TXTdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTdireccionKeyTyped
universales();        // TODO add your handling code here:
    }//GEN-LAST:event_TXTdireccionKeyTyped

    private void txtcontraseña1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontraseña1FocusLost
universales();        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraseña1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    lstUsuariosCargar  federados = new  lstUsuariosCargar(new javax.swing.JFrame(), true);
   federados.setLocationRelativeTo(null);
   federados.setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
     
    }//GEN-LAST:event_jButton1FocusGained

    private void jButton1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1FocusLost

    private void TXTnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTnombreKeyReleased
      String cadena = (TXTnombre.getText()).toUpperCase();
                TXTnombre.setText(cadena);
    }//GEN-LAST:event_TXTnombreKeyReleased

    private void TXTapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTapellidoKeyReleased
       String cadena = (TXTapellido.getText()).toUpperCase();
                TXTapellido.setText(cadena);
    }//GEN-LAST:event_TXTapellidoKeyReleased

    private void TXTdireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTdireccionKeyReleased
       String cadena = (TXTdireccion.getText()).toUpperCase();
                TXTdireccion.setText(cadena);
    }//GEN-LAST:event_TXTdireccionKeyReleased

    private void fecnacimientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fecnacimientoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fecnacimientoKeyReleased

    private void TXTemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTemailKeyReleased
      
    }//GEN-LAST:event_TXTemailKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox LSTsexo;
    public static javax.swing.JTextField TXTapellido;
    public static javax.swing.JTextField TXTcedula;
    public static javax.swing.JTextField TXTdireccion;
    public static javax.swing.JTextField TXTemail;
    public static javax.swing.JTextField TXTnombre;
    public static javax.swing.JTextField TXTtelefono;
    public static javax.swing.JComboBox comboProvincia;
    public static javax.swing.JComboBox combotipousuario;
    public static com.toedter.calendar.JDateChooser fechaInic;
    public static com.toedter.calendar.JDateChooser fecnacimiento;
    public static javax.swing.JLabel foto_label2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    public static javax.swing.JPasswordField txtcontraseña1;
    public static javax.swing.JPasswordField txtcontraseña2;
    // End of variables declaration//GEN-END:variables
public static boolean parametroBasio(){
    if (TXTnombre.getText().equals("")||TXTapellido.getText().equals("")||TXTcedula.getText().equals("")||TXTemail.getText().equals("")||TXTtelefono.getText().equals("")||LSTsexo.getSelectedIndex()==0||fechaInic.getDate()==null||fecnacimiento.getDate()==null||comboProvincia.getSelectedIndex()<1 || combotipousuario.getSelectedIndex()<1)
        return true; 
    else 
        return false ;}

public static  void getDatosIngresados(){
    cedula= Integer.parseInt(TXTcedula.getText());
    nombre=TXTnombre.getText();
    apellido=TXTapellido.getText();
    direccion=TXTdireccion.getText();
    telefono=TXTtelefono.getText();
    email=TXTemail.getText();
  //  convertido = fecha.format(fechaInic.getCalendar().getTime());
     //Formato
    fecha1 = fechaInic.getDate();
    fecha2 = fecnacimiento.getDate();
    fecInicio=fecha.format(fecha1);
    fecNacimiento=fecha.format(fecha2);
    sexo=(String) LSTsexo.getSelectedItem();
    
   
}
public static boolean checkEmail (String email) {

    // Establecer el patron
    Pattern p = Pattern.compile("[-\\w\\.]+@[\\.\\w]+\\.\\w+");

    // Asociar el string al patron
    Matcher m = p.matcher(email);

   // Comprobar si encaja
   return m.matches();

}
public static void nuevo(){
          TXTcedula.setEnabled(true);
        TXTnombre.setEnabled(false);
        TXTapellido.setEnabled(false);
        TXTtelefono.setEnabled(false);
        TXTdireccion.setEnabled(false);
        TXTemail.setEnabled(false);
        fechaInic.setEnabled(false);
        fecnacimiento.setEnabled(false);
        comboProvincia.setEnabled(false);
        foto_label2.setEnabled(false);
        LSTsexo.setEnabled(false);
     combotipousuario.setEnabled(false);
     txtcontraseña1.setEnabled(false);
     txtcontraseña2.setEnabled(false);
        ///////////////////////////
    TXTcedula.setText("");
     TXTnombre.setText("");
     TXTapellido.setText("");
     TXTdireccion.setText("");
     comboProvincia.setSelectedIndex(0);
     fechaInic.setCalendar(null);
     fecnacimiento.setCalendar(null);
     TXTtelefono.setText("");
     TXTemail.setText("");
     LSTsexo.setSelectedIndex(0);
     combotipousuario.setSelectedIndex(0);
     txtcontraseña1.setText("");
     txtcontraseña2.setText("");
   // public static ImageIcon imagenes=new ImageIcon(getClass().getResource("/recursos_iconos/gym2.png").getImage());
    // this.setIconImage(new ImageIcon(getClass().getResource("/recursos_iconos/gym2.png")).getImage());
    String template = System.getProperty("user.dir");
    String path = template+"/src/recursos_iconos/profile-42914_640.png";
     foto_label2.setIcon( new ImageIcon(path));
     
}

public static void guardarUsuarios (){
     if(parametroBasio()){
            JOptionPane.showMessageDialog(null,"Faltan Parametros a ingresar","Error",JOptionPane.ERROR_MESSAGE);}
        else {
            if(!txtcontraseña1.getText().equals(txtcontraseña2.getText())||txtcontraseña2.getText().equals("")){JOptionPane.showMessageDialog(null, "Error las contraseñas no coinciden","Error",JOptionPane.ERROR_MESSAGE); 
            txtcontraseña1.requestFocus();}
            else 
            if (!validar.VerificaCedula(TXTcedula.getText())) {
             JOptionPane.showMessageDialog(null, "Error al digitar Cedula","Error",JOptionPane.ERROR_MESSAGE); 
             TXTcedula.requestFocus();}
             else {getDatosIngresados();
            try {
                if(TXTcedula.isEnabled()==false){
                    if(txt_direccion==null)obj.modificarUsuarioSinfoto(String.valueOf(cedula), nombre, apellido, telefono, direccion, email, sexo, fecInicio, fecNacimiento,comboProvincia.getSelectedItem().toString(),txtcontraseña2.getText(),combotipousuario.getSelectedItem().toString());
                    else obj.modificarUsuario(String.valueOf(cedula), nombre, apellido, telefono, direccion, email, sexo, fecInicio, fecNacimiento,txt_direccion,comboProvincia.getSelectedItem().toString(),txtcontraseña2.getText(),combotipousuario.getSelectedItem().toString());
                           
                }
                else
                obj.ingresarUsuario(cedula, nombre, apellido, telefono, direccion, email, sexo, fecInicio, fecNacimiento,txt_direccion,comboProvincia.getSelectedItem().toString(),combotipousuario.getSelectedItem().toString(),txtcontraseña2.getText());
                nuevo();
            } catch (IOException ex) {
                Logger.getLogger(federadoFrame.class.getName()).log(Level.SEVERE, null, ex);
            }}
            //////////////////
          

        }
    
}
public void universales(){
     miprincipal.planprin=false;
     miprincipal.calendarioprin=false;
     miprincipal.entrenamiento=false;
     miprincipal.entrenamiento2=false;
     miprincipal.entrenadorr=false;
     miprincipal.usuario=true;
     miprincipal.federado=false; }
}
