/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calendario;

import Perfil_Deportivo.Conexion_PerfilDepor;
import Perfil_Deportivo.Progresiones_cargas;
import conexionBase.conexionCargas;
import conexionBase.conexionEntrena;
import force.miprincipal;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author CarlosEfrain
 */
public class calendarioEntreno extends javax.swing.JInternalFrame {
String [] columnaDia ={"Nombres ","dia"};
String [] columnaSemana ={"Nombres ","dia","dia","dia","dia","dia","dia","dia"};
String [] columnaMes ={"Nombres ","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia","dia"};
String [] fechascalen=new String[30];
conexionCalendario  clCalendario; 
public static String iddeportistaFuerza;
public static String nombredeportistaFuerza, categoriaFuerza;
public static String fechaFuerza; 
int columbuscar=0;
int diaBuscar=7;
DateFormat fechaformato = new SimpleDateFormat("yyyy/MM/dd");
Progresiones_cargas porgr;
private TableRowSorter trsfiltro;
    public void filtro() {
    trsfiltro.setRowFilter(RowFilter.regexFilter(txtbuscar.getText(), columbuscar));
    }
    
  
     DefaultTableModel dia=new DefaultTableModel (columnaDia,0);
     DefaultTableModel semana=new DefaultTableModel (columnaSemana,0);
     DefaultTableModel mes=new DefaultTableModel (columnaMes,0);
      Calendar calendario = Calendar.getInstance();
    /**
     * Creates new form calendarioEntreno
     */
public calendarioEntreno() {
         initComponents();
         calcularfecha();
          porgr=new Progresiones_cargas();
         clCalendario=new conexionCalendario();
         clCalendario.calendarioSemana(tblcalendario,"Press banca", fechascalen[0], fechascalen[1], fechascalen[2],fechascalen[3],fechascalen[4], fechascalen[5], fechascalen[6]);  
//clCalendario.calendarioSemana(tblcalendario, "10/11/2014", "11/11/2014", "12/11/2014", "13/11/2014","14/11/2014", "15/11/2014", "16/11/2014");     
jCalendar1.getDayChooser().addPropertyChangeListener(
                new java.beans.PropertyChangeListener() {
 
                    @Override
                    public void propertyChange(java.beans.PropertyChangeEvent evt) {
                        if (evt.getPropertyName().compareTo("day") == 0) {
                            //JOptionPane.showMessageDialog(null,"siii ");
                            calendario.setTime(jCalendar1.getDate());
                            tblcalendario.setRowSorter(null);
                            calcularfecha();
                            if(diaBuscar==7)clCalendario.calendarioSemana(tblcalendario,combocategoriaEjer.getSelectedItem().toString(), fechascalen[0], fechascalen[1], fechascalen[2],fechascalen[3],fechascalen[4], fechascalen[5], fechascalen[6]);
                            else if(diaBuscar==1)clCalendario.calendarioDias(tblcalendario,combocategoriaEjer.getSelectedItem().toString(),fechascalen[0]);
                            else if(diaBuscar==4) clCalendario.calendario4Dias(tblcalendario,combocategoriaEjer.getSelectedItem().toString(), fechascalen[0], fechascalen[1], fechascalen[2], fechascalen[3]);
                        }
                    }
                });


}
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Mi_menu_emergente = new javax.swing.JPopupMenu();
        Progreso = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        combocategoriaEjer = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        txtbuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcalendario = new javax.swing.JTable();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel5 = new javax.swing.JPanel();
        btndia = new javax.swing.JToggleButton();
        btnsemana = new javax.swing.JToggleButton();
        btn4dias = new javax.swing.JToggleButton();

        Progreso.setText("Progreso de Cargas");
        Progreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgresoActionPerformed(evt);
            }
        });
        Mi_menu_emergente.add(Progreso);

        setClosable(true);
        setTitle("CALENDARIO TREINO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/gym2.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        combocategoriaEjer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combocategoriaEjer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Press banca", "Peso muerto", "sentadilla" }));
        combocategoriaEjer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocategoriaEjerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combocategoriaEjer, 0, 214, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(combocategoriaEjer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtbuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });

        jLabel1.setText("Orden de busqueda por: ");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Nombre ");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Cedula ");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108)
                .addComponent(txtbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtbuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblcalendario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblcalendario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tblcalendario.setComponentPopupMenu(Mi_menu_emergente);
        tblcalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcalendarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcalendario);

        jCalendar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jCalendar1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jCalendar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCalendar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCalendar1MouseEntered(evt);
            }
        });
        jCalendar1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jCalendar1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jCalendar1InputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btndia.setText("Día");
        btndia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiaActionPerformed(evt);
            }
        });

        btnsemana.setText("Semana");
        btnsemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsemanaActionPerformed(evt);
            }
        });

        btn4dias.setText("4 Días");
        btn4dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4diasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn4dias, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsemana, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndia, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btndia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn4dias, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btnsemana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiaActionPerformed
         diaBuscar=1;
        tblcalendario.setRowSorter(null);
        clCalendario.calendarioDias(tblcalendario,combocategoriaEjer.getSelectedItem().toString(),fechascalen[0]);  // TODO add your handling code here:
    }//GEN-LAST:event_btndiaActionPerformed

    private void btnsemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsemanaActionPerformed
        diaBuscar=7;
        tblcalendario.setRowSorter(null);
        clCalendario.calendarioSemana(tblcalendario,combocategoriaEjer.getSelectedItem().toString(), fechascalen[0], fechascalen[1], fechascalen[2],fechascalen[3],fechascalen[4], fechascalen[5], fechascalen[6]);        // TODO add your handling code here:
    }//GEN-LAST:event_btnsemanaActionPerformed

    private void btn4diasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4diasActionPerformed
        diaBuscar=4;
        tblcalendario.setRowSorter(null);
        clCalendario.calendario4Dias(tblcalendario,combocategoriaEjer.getSelectedItem().toString(), fechascalen[0], fechascalen[1], fechascalen[2], fechascalen[3]);
    }//GEN-LAST:event_btn4diasActionPerformed

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
txtbuscar.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtbuscar.getText()).toUpperCase();
                txtbuscar.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsfiltro = new TableRowSorter(tblcalendario.getModel());
        tblcalendario.setRowSorter(trsfiltro);         // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
columbuscar=1;        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
columbuscar=0;        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void tblcalendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcalendarioMouseClicked
/*      if (evt.getClickCount() == 1) {
        iddeportistaFuerza=String.valueOf(tblcalendario.getValueAt(tblcalendario.getSelectedRow(), 0));
        nombredeportistaFuerza=String.valueOf(tblcalendario.getValueAt(tblcalendario.getSelectedRow(), 1));
        fechaFuerza=tblcalendario.getColumnName(tblcalendario.getSelectedColumn());
        categoriaFuerza=combocategoriaEjer.getSelectedItem().toString();
        Conexion_PerfilDepor.categoriaGene=combocategoriaEjer.getSelectedItem().toString();
       
        
          Progresiones_cargas porgr=new Progresiones_cargas();
          miprincipal.jDesktopPane1.add(porgr);
          porgr.toFront();
          porgr.setVisible(true);
          
          //JOptionPane.showMessageDialog(null, iddeportistaFuerza+" : "+fechaFuerza);
      }
        */
    }//GEN-LAST:event_tblcalendarioMouseClicked

    private void jCalendar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCalendar1MouseClicked
        
    }//GEN-LAST:event_jCalendar1MouseClicked

    private void jCalendar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jCalendar1AncestorAdded
      
    }//GEN-LAST:event_jCalendar1AncestorAdded

    private void jCalendar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCalendar1MouseEntered
      
    }//GEN-LAST:event_jCalendar1MouseEntered

    private void jCalendar1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jCalendar1CaretPositionChanged
      
    }//GEN-LAST:event_jCalendar1CaretPositionChanged

    private void jCalendar1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jCalendar1InputMethodTextChanged
       
    }//GEN-LAST:event_jCalendar1InputMethodTextChanged

    private void combocategoriaEjerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocategoriaEjerActionPerformed
        if(diaBuscar==7)clCalendario.calendarioSemana(tblcalendario,combocategoriaEjer.getSelectedItem().toString(), fechascalen[0], fechascalen[1], fechascalen[2],fechascalen[3],fechascalen[4], fechascalen[5], fechascalen[6]);
        else if(diaBuscar==1)clCalendario.calendarioDias(tblcalendario,combocategoriaEjer.getSelectedItem().toString(),fechascalen[0]);
        else if(diaBuscar==4) clCalendario.calendario4Dias(tblcalendario,combocategoriaEjer.getSelectedItem().toString(), fechascalen[0], fechascalen[1], fechascalen[2], fechascalen[3]);
    }//GEN-LAST:event_combocategoriaEjerActionPerformed

    private void ProgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgresoActionPerformed
         if (!porgr.isVisible()){
        iddeportistaFuerza=String.valueOf(tblcalendario.getValueAt(tblcalendario.getSelectedRow(), 0));
        nombredeportistaFuerza=String.valueOf(tblcalendario.getValueAt(tblcalendario.getSelectedRow(), 1));
        fechaFuerza=tblcalendario.getColumnName(tblcalendario.getSelectedColumn());
        categoriaFuerza=combocategoriaEjer.getSelectedItem().toString();
        Conexion_PerfilDepor.categoriaGene=combocategoriaEjer.getSelectedItem().toString();
       
         
          porgr=new Progresiones_cargas();
          miprincipal.jDesktopPane1.add(porgr);
          porgr.toFront();
          porgr.setVisible(true);}
    }//GEN-LAST:event_ProgresoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu Mi_menu_emergente;
    private javax.swing.JMenuItem Progreso;
    private javax.swing.JToggleButton btn4dias;
    private javax.swing.JToggleButton btndia;
    private javax.swing.JToggleButton btnsemana;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox combocategoriaEjer;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcalendario;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
public void calcularfecha(){
    for (int i = 0; i < 30; i++) {
        fechascalen[i]=fechaformato.format(calendario.getTime()); 
        calendario.add(Calendar.DAY_OF_MONTH, 1);
    }
}
}
