/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package entrenamiento;

import CargarEntrenamiento.lstEntrenamiento;
import conexionBase.conexionEntrena;
import force.miprincipal;
import static force.miprincipal.jDesktopPane1;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;

/**
 *
 * @author CarlosEfrain
 */
public class Entrenamiento extends javax.swing.JInternalFrame  {

    String [] columna ={"semana ","dia","peso"};
public static double [] valor;
    JTextField txte= new JTextField();
public static int dia, sema,lleno=0;
public static int llena=0;
public String texto; 
public static conexionEntrena obj=new conexionEntrena();
 
// Esta es la clase interna. Está definida DENTRO de MiVentana


  
    public static DefaultTableModel encabezado;
    /**
     * Creates new form Entrenamiento
     */
    public Entrenamiento() {
        initComponents();
        encabezado= (DefaultTableModel) tbltabla.getModel();
        tbltabla.setModel(encabezado); //llenad del encabezado
        TableColumn tc= tbltabla.getColumnModel().getColumn(2);
        TableCellEditor te  =new DefaultCellEditor(txte);
        tc.setCellEditor(te);
        
       txte.addKeyListener(new KeyAdapter()
          {
           @Override
           public void keyTyped(KeyEvent e )
                  {
               try {
                     Double.parseDouble(txte.getText()+e.getKeyChar());
                 } catch (Exception ed) {
                     e.consume();
        } 
                  }});
        
/*        
TableModel model = jtable.getModel();
int selectedRow = jtable.getSelectedRow();

// Supongamos que es un JTable de 3 columnas
String columna1 = (String) model.getValueAt(selectedRow, 0);
String columna2 = (String) model.getValueAt(selectedRow, 1);
String columna3 = (String) model.getValueAt(selectedRow, 2);

// Puedes agrupar los tres valores en un objeto para mayor claridad del código
FilaTabla fila = new FilaTabla();
fila.setColumna1(columna1);
fila.setColumna2(columna2);
fila.setColumna3(columna3);
*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcodentrenador = new javax.swing.JTextField();
        btnnombre = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtnombreentrenador = new javax.swing.JTextField();
        btncodigoentrenador = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        combCategoria = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btncargar = new javax.swing.JButton();
        comboDias = new javax.swing.JComboBox();
        comboSemana = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbltabla = new javax.swing.JTable();

        setClosable(true);
        setTitle("ENTRENAMIENTO");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/gym2.png"))); // NOI18N
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del Entrenamiento ");

        txtnombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Codigo del entrenador ");

        txtcodentrenador.setEditable(false);
        txtcodentrenador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcodentrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodentrenadorActionPerformed(evt);
            }
        });

        btnnombre.setText("...");
        btnnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre del entrenador ");

        txtnombreentrenador.setEditable(false);
        txtnombreentrenador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btncodigoentrenador.setText("...");
        btncodigoentrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncodigoentrenadorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tipo Entrenamiento");

        combCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Press banca", "Peso muerto", "sentadilla " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombre)
                            .addComponent(combCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnnombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcodentrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncodigoentrenador))
                    .addComponent(txtnombreentrenador))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(combCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodentrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btncodigoentrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombreentrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Dias de entrenamiento ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Semana de entrenamiento ");

        btncargar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btncargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/graphics.stats-32.png"))); // NOI18N
        btncargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarActionPerformed(evt);
            }
        });

        comboDias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "seleccione días", "1", "2", "3", "4", "5", "6", "7" }));
        comboDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiasActionPerformed(evt);
            }
        });

        comboSemana.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboSemana.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "seleccione semanas ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48" }));
        comboSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSemanaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/eliminard.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncargar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboSemana, javax.swing.GroupLayout.Alignment.LEADING, 0, 166, Short.MAX_VALUE)
                            .addComponent(comboDias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(comboSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbltabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semana", "Dia", "Peso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbltabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltablaMouseClicked(evt);
            }
        });
        tbltabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbltablaKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(tbltabla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarActionPerformed
tblllena();
        if (tbltabla.getRowCount()<1||llena==1){
           JOptionPane.showMessageDialog(null," Error faltan pesos en a tabla","Error",JOptionPane.ERROR_MESSAGE);}
    //limpiarTabla(tbltabla);
else {
 dia=comboDias.getSelectedIndex();
 sema=comboSemana.getSelectedIndex();
 int dt=0,mt=1;
 //migrafic.llenas1();
 //migrafic.borrars1();
 valor=new double[tbltabla.getRowCount()];
 for( int s=0;s < tbltabla.getRowCount(); s++ ){   
     valor[s]=Double.parseDouble(tbltabla.getValueAt(s, 2).toString());
   }
  grafica migrafic=new grafica();
  //migrafic.llenarXY(valor);
//migrafica gfica = new migrafica();
 //       miprincipal.jDesktopPane1.add(gfica);  
 //       gfica.show();
  graficaEntrenamiento  dialog32 = new graficaEntrenamiento(new javax.swing.JFrame(), true);
  dialog32.setLocationRelativeTo(null);
  dialog32.setVisible(true);}
 universales();
// TODO add your handling code here:
    }//GEN-LAST:event_btncargarActionPerformed

    private void btncodigoentrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncodigoentrenadorActionPerformed
universales();
   lstEntrenadores  dialog = new lstEntrenadores(new javax.swing.JFrame(), true);
   dialog.setLocationRelativeTo(null);
   dialog.setVisible(true);
        /*listarEntrenador lstentranador = new listarEntrenador();
      miprincipal.jDesktopPane1.add(lstentranador);
      lstentranador.toFront();
      lstentranador.setVisible(true);*/
       // TODO add your handling code here:
    }//GEN-LAST:event_btncodigoentrenadorActionPerformed

    private void btnnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnombreActionPerformed
   universales();
   lstEntrenamiento2  dialog2 = new lstEntrenamiento2(new javax.swing.JFrame(), true);
   dialog2.setLocationRelativeTo(null);
   dialog2.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btnnombreActionPerformed

    private void txtcodentrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodentrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodentrenadorActionPerformed

    private void comboDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiasActionPerformed
     
        if(comboDias.getSelectedIndex()!=0 && comboSemana.getSelectedIndex()!=0){  
    if (!conexionEntrena.cargando){
  limpiarTabla(tbltabla);
 dia=comboDias.getSelectedIndex();
 sema=comboSemana.getSelectedIndex();
 for( int s=1;s <= sema; s++ ){       
 for ( int d=1;d <= dia; d++ ){
                encabezado.addRow(new Object[]{"SEMANA "+s,"DIA "+d,""});
             }
 }
     } }       // TODO add your handling code here:
    }//GEN-LAST:event_comboDiasActionPerformed

    private void comboSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSemanaActionPerformed
if(comboDias.getSelectedIndex()!=0 && comboSemana.getSelectedIndex()!=0){  
   if (!conexionEntrena.cargando){
 limpiarTabla(tbltabla);
 dia=comboDias.getSelectedIndex();
 sema=comboSemana.getSelectedIndex();
 for( int s=1;s <= sema; s++ ){       
 for ( int d=1;d <= dia; d++ ){
                encabezado.addRow(new Object[]{"SEMANA "+s,"DIA "+d,""});
             }
 }
     }  }      // TODO add your handling code here:
    }//GEN-LAST:event_comboSemanaActionPerformed

    private void tbltablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltablaMouseClicked
      
    }//GEN-LAST:event_tbltablaMouseClicked

    private void tbltablaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbltablaKeyTyped
  try {
            Double.parseDouble(txte.getText()+evt.getKeyChar());
        } catch (Exception e) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tbltablaKeyTyped

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
 universales();    // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
       texto=txtnombre.getText();
       universales();
    }//GEN-LAST:event_txtnombreKeyTyped

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
   JOptionPane.showMessageDialog(null,"gano :)");
    // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
        String cadena = (txtnombre.getText()).toUpperCase();
                txtnombre.setText(cadena);
    }//GEN-LAST:event_txtnombreKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!txtnombre.isEnabled()){
        if(obj.consultarEntrenamientoCargado(lstEntrenamiento2.codigo)){
         JOptionPane.showMessageDialog(null,"No se puede eliminar, hay deportistas con este entreno");
         }
         else{
        obj.eliminarEntreno(lstEntrenamiento2.codigo);
        obj.eliminarPlanEntreno(lstEntrenamiento2.codigo);
        JOptionPane.showMessageDialog(null,"Entrenamiento borrado correctamente");
        nuevo();
        }}
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncargar;
    private javax.swing.JButton btncodigoentrenador;
    private javax.swing.JButton btnnombre;
    public static javax.swing.JComboBox combCategoria;
    public static javax.swing.JComboBox comboDias;
    public static javax.swing.JComboBox comboSemana;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane6;
    public static javax.swing.JTable tbltabla;
    public static javax.swing.JTextField txtcodentrenador;
    public static javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txtnombreentrenador;
    // End of variables declaration//GEN-END:variables

 private static  void tblllena() {
     llena=0;
     int cont2=0;
     for( int s=1;s <= sema; s++ ){       
     for ( int d=1;d <= dia; d++ ){
         if(String.valueOf(tbltabla.getValueAt(cont2,2)).equals(""))llena=1; 
            cont2=cont2+1; }}}

public static void limpiarTabla(JTable tabla){
        try {
            DefaultTableModel modelo=(DefaultTableModel) tabla.getModel();
            int filas=tabla.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }
public static void guardarEntrenamiento (){
  
     double semana, di, peso;
    String nombreentreno= (String) txtnombre.getText();
    obj = new conexionEntrena();
    
    obj.consulNombreEntreno(nombreentreno);
    String n=obj.getnombreEntreno();
    tblllena();
    
    if(n.equals(nombreentreno) && txtnombre.isEnabled()==true){
            JOptionPane.showMessageDialog(null," nombre del entrenamiento repetido","Advertencia",JOptionPane.WARNING_MESSAGE);}
    else {if (txtnombreentrenador.getText().equals(""))
            JOptionPane.showMessageDialog(null," seleccione un entrenador","Advertencia",JOptionPane.WARNING_MESSAGE);
    else if(dia==0 || sema==0){
           JOptionPane.showMessageDialog(null," Error en el periodo de entreno","Error",JOptionPane.ERROR_MESSAGE);}
    else if (llena==1){
           JOptionPane.showMessageDialog(null," Error faltan pesos en a tabla","Error",JOptionPane.ERROR_MESSAGE);}
    else {
        String categoria= String.valueOf(combCategoria.getSelectedItem());
        int codentrenador=Integer.parseInt(txtcodentrenador.getText());
        int idget;
        int cont=0;
        ////////////// variables 
    if (txtnombre.isEnabled()){
       obj.ingresarEntreno(nombreentreno, categoria, codentrenador,sema,dia);
       obj.consulIdEntreno(nombreentreno);

       idget=obj.getId();
         //   JOptionPane.showMessageDialog(null, String.valueOf(idget));
     cont=0;
     for( int s=1;s <= sema; s++ ){       
     for ( int d=1;d <= dia; d++ ){
                    peso= Double.parseDouble((String) encabezado.getValueAt(cont,2));
                    obj.ingresarP(s, d, peso,idget);
                    cont=cont+1;
             }}
        }
    else {
        
        try {
            obj.ModificarEntreno(lstEntrenamiento2.codigo, categoria, codentrenador,sema,dia);
        obj.eliminarPlanEntreno(lstEntrenamiento2.codigo);
       
     cont=0;

     for( int s=1;s <= sema; s++ ){       
     for ( int d=1;d <= dia; d++ ){
                    peso= Double.parseDouble( (String) encabezado.getValueAt(cont,2));
                    obj.ingresarP(s, d, peso,Integer.parseInt(lstEntrenamiento2.codigo));
                    cont=cont+1;
             }}
     JOptionPane.showMessageDialog(null,"Modificación exitosa");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de modificacion"+e.getMessage());
        }
        
                }
     nuevo();
                
    }//////////////////////////////////////////////////////FIN DEL ELSE 
 }
}
public static void nuevo(){
   txtcodentrenador.setText("");
       txtnombreentrenador.setText("");
       combCategoria.setSelectedIndex(0);
       comboDias.setSelectedIndex(0);
       comboSemana.setSelectedIndex(0);
       limpiarTabla(tbltabla);
        dia=comboDias.getSelectedIndex();
 sema=comboSemana.getSelectedIndex();
 txtnombre.setText("");
 txtnombre.setEnabled(true);
}


public void universales(){
     miprincipal.planprin=false;
     miprincipal.calendarioprin=false;
     miprincipal.entrenamiento=true;
     miprincipal.usuario=false;
     miprincipal.federado=false; 
     miprincipal.entrenamiento2=false;
     miprincipal.entrenadorr=false;}
      
    }
