/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package imc;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CarlosEfrain
 */
public class imc extends javax.swing.JInternalFrame {
DecimalFormatSymbols simbolos = new DecimalFormatSymbols();
Calendar calendario = Calendar.getInstance();
DecimalFormat formatter;
conexionIMc objimc= new conexionIMc();
SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy/MM/dd");
 public static double[] imc;
    public static String[] fecha;
    /**
     * Creates new form imc
     */
    public imc() {
        initComponents();
        simbolos.setDecimalSeparator('.');
        formatter = new DecimalFormat("#0.00",simbolos); 
        choserfecha.setCalendar(calendario);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableindice = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        choserfecha = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btnew = new javax.swing.JButton();
        btngrafico = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtpeso2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtaltura2 = new javax.swing.JTextField();
        txtcintura = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcuello = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcadera = new javax.swing.JTextField();
        txtigc = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtimc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpeso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtaltura = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtmcm = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setClosable(true);

        tableindice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "FECHA", "PESO", "IMC", "IGC", "MCM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableindice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tableindiceKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tableindice);

        jLabel14.setText("Cedula");

        jLabel15.setText("Nombre ");

        txtcedula.setEditable(false);

        txtnombre.setEditable(false);

        jLabel16.setText("Fecha ");

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/btn_guardar.png"))); // NOI18N
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/nuevoicono.png"))); // NOI18N
        btnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewActionPerformed(evt);
            }
        });

        btngrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/graphics.stats-32.png"))); // NOI18N
        btngrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngraficoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtpeso2.setEditable(false);
        txtpeso2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpeso2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpeso2KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Peso ");

        txtaltura2.setEditable(false);
        txtaltura2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtcintura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcintura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcinturaKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Cintura(Cm)");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("altura");

        txtcuello.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcuello.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcuelloKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cuello(Cm)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Cadero(Mujer)");

        txtcadera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaderaActionPerformed(evt);
            }
        });
        txtcadera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcaderaKeyTyped(evt);
            }
        });

        txtigc.setEditable(false);
        txtigc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("IGC");

        jLabel6.setText("2-IGC (indice de grasa corporal)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtpeso2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtigc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcuello)
                                    .addComponent(txtcadera, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcintura)
                            .addComponent(txtaltura2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtpeso2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtaltura2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcuello, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtcintura, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcadera, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtigc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("1-Imc (indice de masa corporal) ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Peso (KG)");

        txtimc.setEditable(false);
        txtimc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("altura(Cm)");

        txtpeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpesoKeyTyped(evt);
            }
        });

        jLabel4.setText("¿que indica el IMC?");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Imc");

        txtaltura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtaltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtalturaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtaltura, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtimc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaltura, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtimc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/musculos.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("3- Masa corporal magra ");

        txtmcm.setEditable(false);
        txtmcm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("MCM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(choserfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtmcm)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnew, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btngrafico)
                                .addGap(90, 90, 90)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)
                        .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jLabel16))
                    .addComponent(choserfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btngrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmcm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpeso2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpeso2KeyTyped
        if(txtaltura2.getText().equals("") && txtcuello.getText().equals("")&&txtcintura.getText().equals("")){}
        else {
            calcularigc(Double.parseDouble(txtcuello.getText()), Double.parseDouble(txtaltura2.getText()),Double.parseDouble( txtcintura.getText()));
        }
    }//GEN-LAST:event_txtpeso2KeyTyped

    private void txtpesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesoKeyTyped
     String valor="";
        try {
            Double.parseDouble(txtpeso.getText()+evt.getKeyChar());
            txtpeso2.setText(txtpeso.getText()+evt.getKeyChar());
            valor=txtpeso.getText()+evt.getKeyChar();
        } catch (NumberFormatException e) {
            txtpeso2.setText(txtpeso.getText());
              valor=txtpeso.getText();
            evt.consume();}
       if (!valor.equals("")&&!txtaltura.getText().equals(""))
       {double imc=Double.parseDouble(valor)/((Double.parseDouble(txtaltura.getText())/100)*(Double.parseDouble(txtaltura.getText())/100));
       txtimc.setText(String.valueOf(formatter.format(imc)));
       }
      if(!txtcintura.getText().equals("")&&!txtaltura2.getText().equals("") && !txtcuello.getText().equals("")&&txtcadera.getText().equals("")&& !txtpeso.getText().equals(""))
      calcularigc(Double.parseDouble(txtcuello.getText()), Double.parseDouble(txtaltura2.getText()),Double.parseDouble( txtcintura.getText()));
      else  if(!txtcintura.getText().equals("")&&!txtaltura2.getText().equals("") && !txtcuello.getText().equals("")&&!txtcadera.getText().equals("")&& !txtpeso.getText().equals(""))
      calcularigcMujer(Double.parseDouble(txtcuello.getText()), Double.parseDouble(txtaltura2.getText()),Double.parseDouble( txtcintura.getText()),Double.parseDouble(txtcadera.getText()));
    }//GEN-LAST:event_txtpesoKeyTyped

    private void txtalturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtalturaKeyTyped
         String valor=""; 
        try {
            Double.parseDouble(txtaltura.getText()+evt.getKeyChar());
            txtaltura2.setText(txtaltura.getText()+evt.getKeyChar());
            valor=txtaltura.getText()+evt.getKeyChar();
        } catch (NumberFormatException e) {
            txtaltura2.setText(txtaltura.getText());
             valor=txtaltura.getText();
            evt.consume();}
        if (!txtpeso.getText().equals("")&&!valor.equals(""))
       {double imc=Double.parseDouble(txtpeso.getText())/((Double.parseDouble(valor)/100)*(Double.parseDouble(valor)/100));
        txtimc.setText(String.valueOf(formatter.format(imc)));
       }
      if(!txtcintura.getText().equals("")&&!txtaltura2.getText().equals("") && !txtcuello.getText().equals("")&&txtcadera.getText().equals(""))
      calcularigc(Double.parseDouble(txtcuello.getText()), Double.parseDouble(txtaltura2.getText()),Double.parseDouble( txtcintura.getText()));
      else  if(!txtcintura.getText().equals("")&&!txtaltura2.getText().equals("") && !txtcuello.getText().equals("")&&!txtcadera.getText().equals(""))
      calcularigcMujer(Double.parseDouble(txtcuello.getText()), Double.parseDouble(txtaltura2.getText()),Double.parseDouble( txtcintura.getText()),Double.parseDouble(txtcadera.getText()));
    }//GEN-LAST:event_txtalturaKeyTyped

    private void txtcuelloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcuelloKeyTyped
     String variable="";
        try {
            Double.parseDouble(txtcuello.getText()+evt.getKeyChar());
            variable=txtcuello.getText()+evt.getKeyChar();
        } catch (NumberFormatException e) {
            variable=txtcuello.getText();
            evt.consume();}
    if(!txtcintura.getText().equals("")&&!txtaltura2.getText().equals("") && !variable.equals("")&& txtcadera.getText().equals("") )
      calcularigc(Double.parseDouble(variable), Double.parseDouble(txtaltura2.getText()),Double.parseDouble( txtcintura.getText()));
    else  if(!txtcintura.getText().equals("")&&!txtaltura2.getText().equals("") && !variable.equals("")&&!txtcadera.getText().equals("") ){
         calcularigcMujer(Double.parseDouble(variable), Double.parseDouble(txtaltura2.getText()),Double.parseDouble( txtcintura.getText()),Double.parseDouble(txtcadera.getText()));
    }
    }//GEN-LAST:event_txtcuelloKeyTyped

    private void txtcinturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcinturaKeyTyped
       String variable="";
        try {
            Double.parseDouble(txtcintura.getText()+evt.getKeyChar());
            variable=txtcintura.getText()+evt.getKeyChar();
        } catch (NumberFormatException e) {
            variable=txtcintura.getText();
            evt.consume();}
    if(!variable.equals("")&&!txtaltura2.getText().equals("") && !txtcuello.getText().equals("")&& txtcadera.getText().equals(""))
          calcularigc(Double.parseDouble(txtcuello.getText()), Double.parseDouble(txtaltura2.getText()),Double.parseDouble( variable));
    else if(!variable.equals("")&&!txtaltura2.getText().equals("") && !txtcuello.getText().equals("")&& !txtcadera.getText().equals(""))
          calcularigcMujer(Double.parseDouble(txtcuello.getText()), Double.parseDouble(txtaltura2.getText()),Double.parseDouble( variable),Double.parseDouble(txtcadera.getText()));
    }//GEN-LAST:event_txtcinturaKeyTyped

    private void txtcaderaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaderaKeyTyped
        //  =495/(1.29579-0.35004(log(cintura+cadera-cuello))+0.22100(log(altura)))-450
        String variable="";
        try {
            Double.parseDouble(txtcadera.getText()+evt.getKeyChar());
            variable=txtcadera.getText()+evt.getKeyChar();
        } catch (NumberFormatException e) {
            variable=txtcadera.getText();
            evt.consume();}
        try {
            
        } catch (Exception e) {
        }
    if(!variable.equals("")&&!txtaltura2.getText().equals("") && !txtcuello.getText().equals("")&&!txtcintura.getText().equals(""))
        calcularigcMujer(Double.parseDouble(txtcuello.getText()), Double.parseDouble(txtaltura2.getText()),Double.parseDouble( txtcintura.getText()),Double.parseDouble(variable));
    }//GEN-LAST:event_txtcaderaKeyTyped

    private void txtcaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaderaActionPerformed
      
    
    }//GEN-LAST:event_txtcaderaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   lstDeportistasIMC  federados2 = new lstDeportistasIMC (new javax.swing.JFrame(), true);
   federados2.setLocationRelativeTo(null);
   federados2.setVisible(true); 
    if(!txtcedula.getText().equals("")){
      
        ///////////
        try {
         //objen.consultarEntrenamientoTotal(txtcedula.getText());
         objimc.consultarCargasTotal_IMC(tableindice, txtcedula.getText());
         } catch (Exception e) {
       }
   }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        try {
            Double.parseDouble(txtmcm.getText());
            // idfederado, imc, igc, altura, peso, mcm,fecha
            if (objimc.consultarRegistroRepetidoIMC(txtcedula.getText(), formatoDelTexto.format(choserfecha.getDate())))
               JOptionPane.showMessageDialog(null,"El registro en esta fecha ya existe ");
            else  {
            objimc.ingresarIMC(txtcedula.getText(), Double.parseDouble(txtimc.getText()), Double.parseDouble(txtigc.getText()), Double.parseDouble(txtaltura.getText()), Double.parseDouble(txtpeso.getText()), Double.parseDouble(txtmcm.getText()), formatoDelTexto.format(choserfecha.getDate()));
            objimc.consultarCargasTotal_IMC(tableindice, txtcedula.getText());
            nuevo();}
        } catch (Exception e) {
            
        }

    }//GEN-LAST:event_btnguardarActionPerformed

    private void tableindiceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableindiceKeyTyped
     int i=evt.getKeyChar();
     if (i==8){
     if(!txtcedula.getText().equals("")){  
      int j=JOptionPane.showConfirmDialog(null,"Esta seguro de eliminar este registro","Aceptar",JOptionPane.INFORMATION_MESSAGE);
        if(j==0) {
        objimc.eliminarIMC(txtcedula.getText(), tableindice.getValueAt(tableindice.getSelectedRow(), 0).toString());
        objimc.consultarCargasTotal_IMC(tableindice, txtcedula.getText());
        }}}
    }//GEN-LAST:event_tableindiceKeyTyped

    private void btnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewActionPerformed
      nuevo();
    }//GEN-LAST:event_btnewActionPerformed

    private void btngraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngraficoActionPerformed
          imc=new double[tableindice.getRowCount()];
       fecha=new String[tableindice.getRowCount()];
 for( int s=0;s < tableindice.getRowCount(); s++ ){   
     imc[s]=Double.parseDouble(tableindice.getValueAt(s, 4).toString());
     fecha[s]=String.valueOf(tableindice.getValueAt(s, 0).toString());
   }
    graficaIMC migrafic=new graficaIMC();
  //migrafic.llenarXY(valor);
    //migrafica gfica = new migrafica();
 //       miprincipal.jDesktopPane1.add(gfica);  
 //       gfica.show();
    graficaIMC1  dialog32 = new graficaIMC1(new javax.swing.JFrame(), true);
    dialog32.setLocationRelativeTo(null);
    dialog32.setVisible(true);
    }//GEN-LAST:event_btngraficoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnew;
    private javax.swing.JButton btngrafico;
    private javax.swing.JButton btnguardar;
    private com.toedter.calendar.JDateChooser choserfecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableindice;
    private javax.swing.JTextField txtaltura;
    private javax.swing.JTextField txtaltura2;
    private javax.swing.JTextField txtcadera;
    public static javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcintura;
    private javax.swing.JTextField txtcuello;
    private javax.swing.JTextField txtigc;
    private javax.swing.JTextField txtimc;
    private javax.swing.JTextField txtmcm;
    public static javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpeso;
    private javax.swing.JTextField txtpeso2;
    // End of variables declaration//GEN-END:variables
public void calcularigc(double cuello, double altura, double cintura){
    double igc,mcm;
    igc=495/(1.0324-0.19077*Math.log10(cintura-cuello)+0.15456*(Math.log10(altura)))-450;
    txtigc.setText(String.valueOf(formatter.format(igc)));
    mcm=Double.parseDouble(txtpeso.getText())-(Double.parseDouble(txtpeso.getText())*(igc/100));
    txtmcm.setText(String.valueOf(formatter.format(mcm)));
}
public void calcularigcMujer(double cuello, double altura, double cintura, double cadera){
    double igc,mcm;
   // =495/(1.29579-0.35004(log(cintura+cadera-cuello))+0.22100(log(altura)))-450
    igc=495/(1.29579-0.35004*(Math.log10(cintura+cadera-cuello))+0.22100*(Math.log10(altura)))-450;
    txtigc.setText(String.valueOf(formatter.format(igc)));
    mcm=Double.parseDouble(txtpeso.getText())-(Double.parseDouble(txtpeso.getText())*(igc/100));
    txtmcm.setText(String.valueOf(formatter.format(mcm)));
}
void nuevo(){
    
   txtaltura.setText("");
   txtaltura2.setText("");
   txtcadera.setText("");
   txtcintura.setText("");
   txtcuello.setText("");
   txtigc.setText("");
   txtimc.setText("");
   txtmcm.setText("");
   txtpeso.setText("");
   txtpeso2.setText("");
}
}
