/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package force;

import CargarEntrenamiento.cargarEntreno;
import CargarEntrenamiento.reporteador;
import Perfil_Deportivo.EntrenamientoCargado;
import Perfil_Deportivo.Progresiones_cargas;
import calendario.calendarioEntreno;
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaBlackStarLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaBlueMoonLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaBlueSteelLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaGreenDreamLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaMauveMetallicLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaSimple2DLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaStandardLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaWhiteVisionLookAndFeel;
import entrenamiento.Entrenamiento;
import entrenamiento.Entrenamiento2;

import force.listar.TimeSeriesChartDemo;
import graficoComparacion.GraficoComparacion;
import imc.imc;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jfree.chart.demo.TimeSeriesChartDemo1;
import org.jfree.ui.RefineryUtilities;
import todosPersonas.Entrenador;
import todosPersonas.Usuarios;
import todosPersonas.conexionUsuarios;
import todosPersonas.federadoFrame;

/**
 *
 * @author CarlosEfrain
 */
public class miprincipal extends javax.swing.JFrame {
    public static boolean planprin=false;
    public static boolean calendarioprin=false;
    public static boolean entrenamiento=false;
    public static boolean entrenamiento2=false;
    public static boolean usuario=false;
    public static boolean entrenadorr=false;
    public static boolean federado=false;
    conexionUsuarios userprincipal=new conexionUsuarios();
    Calendar calendarfech=Calendar.getInstance();
    Date  fechadate;
  Usuarios miusuario=null ;
 federadoFrame federados =null;
 Entrenamiento entrenamientofr =null;
 calendarioEntreno calendario = null;
 cargarEntreno cargartreino = null;
 DateFormat fecha = new SimpleDateFormat("yyyy/MM/dd"); 
 EntrenamientoCargado cargas4;
 reporteador repor;
 imc imc1;
 Entrenamiento2 entre2;
 Entrenador entrenador;
 public static String tipousuario="";
 /**
 
     * Creates new form miprincipal
     */
    public miprincipal() {
        initComponents();
        entrenador =new Entrenador();
        entre2= new Entrenamiento2();
        cargas4=new EntrenamientoCargado();
        repor= new reporteador();
        imc1= new imc();
     this.setLocationRelativeTo(null);
 //Hora y Fecha del Sistema con EdisonCor
//        new Reloj().fecha(lbl_fecha);
        Reloj hilo = new Reloj(relolabel);
        hilo.start();
        fechlabel.setText("  "+fecha.format(calendarfech.getTime())+" - ");
        //lbl_hora.setDescription("Hora del Sistema");

        //cambio();
        //salir del sistema cerrando el jframe
          
        userprincipal.consultarUsuarioFoto(login.cedulalogin);
        this.setIconImage(new ImageIcon(getClass().getResource("/recursos_iconos/gym2.png")).getImage());
        if (tipousuario.equals("NORMAL"))menucontrol.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel7 = new javax.swing.JPanel();
        foto_label2 = new javax.swing.JLabel();
        nombrePrincipal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton5 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        fechlabel = new javax.swing.JLabel();
        relolabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuentrenamiento = new javax.swing.JMenuItem();
        menuentrenamiento1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        menucontrol = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        menucalendario = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jMenuItem10.setText("jMenuItem10");

        jMenu6.setText("File");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar4.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FORCE");

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        foto_label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/profile-42914_640.png"))); // NOI18N
        foto_label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foto_label2foto_labelMouseClicked(evt);
            }
        });

        nombrePrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombrePrincipal.setText("Usuario");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foto_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nombrePrincipal)
                .addGap(50, 50, 50))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(foto_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombrePrincipal)
                .addContainerGap())
        );

        jDesktopPane1.add(jPanel7);
        jPanel7.setBounds(1160, 0, 160, 200);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/force2.png"))); // NOI18N
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(140, 150, 1120, 480);

        jToolBar1.setRollover(true);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/nuevoicono.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/btn_guardar.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        fechlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechlabel.setText("fecha");
        jToolBar1.add(fechlabel);

        relolabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        relolabel.setText(" horaaa ");
        jToolBar1.add(relolabel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1160, 40);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("ARCHIVO");

        jMenuItem2.setText("Nuevo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Guardar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setText("Plan ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuentrenamiento.setText("Entrenamiento");
        menuentrenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuentrenamientoActionPerformed(evt);
            }
        });
        jMenu1.add(menuentrenamiento);

        menuentrenamiento1.setText("Entrenamiento 1RM");
        menuentrenamiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuentrenamiento1ActionPerformed(evt);
            }
        });
        jMenu1.add(menuentrenamiento1);

        jMenuItem3.setText("Deportista");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem13.setText("Reportes");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuBar1.add(jMenu1);

        menucontrol.setText("CONTROL");

        jMenuItem18.setText("Grafica");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        menucontrol.add(jMenuItem18);

        menucalendario.setText("Calendario");
        menucalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucalendarioActionPerformed(evt);
            }
        });
        menucontrol.add(menucalendario);

        jMenuItem11.setText("Entrenamientos cargados");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        menucontrol.add(jMenuItem11);

        jMenuItem12.setText("Imc");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        menucontrol.add(jMenuItem12);

        jMenuItem8.setText("Usuario");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menucontrol.add(jMenuItem8);

        jMenuItem9.setText("Entrenador");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menucontrol.add(jMenuItem9);

        jMenuBar1.add(menucontrol);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1317, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    
       if(cargartreino==null){ cargartreino = new cargarEntreno();
      jDesktopPane1.add(cargartreino);  
       cargartreino.show();}
        else  if(cargartreino.isClosed())  
        {  cargartreino = new cargarEntreno();
      jDesktopPane1.add(cargartreino);  
       cargartreino.show();}
       // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menucalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucalendarioActionPerformed
       
       if(calendario==null){ calendario = new calendarioEntreno();
      jDesktopPane1.add(calendario);  
       calendario.show(); }
        else  if(calendario.isClosed())  
        {  calendario = new calendarioEntreno();
      jDesktopPane1.add(calendario);  
       calendario.show();}
       // TODO add your handling code here:
    }//GEN-LAST:event_menucalendarioActionPerformed

    private void menuentrenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuentrenamientoActionPerformed
if(entrenamientofr==null){ entrenamientofr = new Entrenamiento();
        jDesktopPane1.add(entrenamientofr);  
        entrenamientofr.show(); }
        else  if(entrenamientofr.isClosed())  
        {  entrenamientofr = new Entrenamiento();
        jDesktopPane1.add(entrenamientofr);  
        entrenamientofr.show();}// TODO add your handling code here:
    }//GEN-LAST:event_menuentrenamientoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if(federados==null){ federados = new federadoFrame();
            jDesktopPane1.add(federados);  
             federados.show(); }
        else  if(federados.isClosed())  
        {  federados = new federadoFrame();
            jDesktopPane1.add(federados);  
             federados.show();}
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if(miusuario==null){miusuario = new Usuarios();
            jDesktopPane1.add(miusuario);  
            miusuario.show();}
        else  if(miusuario.isClosed())  
        {  miusuario = new Usuarios();
            jDesktopPane1.add(miusuario);  
            miusuario.show();} // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void foto_label2foto_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foto_label2foto_labelMouseClicked

      
    }//GEN-LAST:event_foto_label2foto_labelMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if(entrenamiento && !entrenamientofr.isClosed()) Entrenamiento.nuevo();
else if(entrenamiento2 && !entre2.isClosed()) Entrenamiento2.nuevo();
else if(entrenadorr && !entrenador.isClosed()) Entrenador.nuevo();
      else if(usuario&& !miusuario.isClosed())Usuarios.nuevo();
      else if (federado && !federados.isClosed())federadoFrame.nuevo();
      else if (planprin && !cargartreino.isClosed())cargarEntreno.nuevo();           // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

      if(entrenamiento && !entrenamientofr.isClosed()) Entrenamiento.guardarEntrenamiento();
      else if(entrenadorr && !entrenador.isClosed())Entrenador.guardarFederados();
      else if(entrenamiento2 && !entre2.isClosed()) Entrenamiento2.guardarEntrenamiento();
      else if(usuario&& !miusuario.isClosed())Usuarios.guardarUsuarios();
      else if (federado && !federados.isClosed())federadoFrame.guardarFederados();
      else if (planprin && !cargartreino.isClosed())cargarEntreno.guardarPlanEntreno();       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
if(entrenamiento && !entrenamientofr.isClosed()) Entrenamiento.nuevo();
else if(entrenamiento2 && !entre2.isClosed()) Entrenamiento2.nuevo();
else if(entrenamiento2 && !entre2.isClosed()) Entrenamiento2.nuevo();
      else if(usuario&& !miusuario.isClosed())Usuarios.nuevo();
      else if (federado && !federados.isClosed())federadoFrame.nuevo();
      else if (planprin && !cargartreino.isClosed())cargarEntreno.nuevo();         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
      if(entrenamiento && !entrenamientofr.isClosed()) Entrenamiento.guardarEntrenamiento();
       else if(entrenadorr && !entrenador.isClosed())Entrenador.guardarFederados();
      else if(entrenamiento2 && !entre2.isClosed()) Entrenamiento2.guardarEntrenamiento();
      else if(usuario&& !miusuario.isClosed())Usuarios.guardarUsuarios();
      else if (federado && !federados.isClosed())federadoFrame.guardarFederados();
      else if (planprin && !cargartreino.isClosed())cargarEntreno.guardarPlanEntreno();          // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
           GraficoComparacion cargas2 = new GraficoComparacion();
            jDesktopPane1.add(cargas2);  
            cargas2.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
       if (!cargas4.isVisible()){
      cargas4=new EntrenamientoCargado();
      jDesktopPane1.add(cargas4);
      cargas4.toFront();
      cargas4.setVisible(true);}
    
    
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        
      if (!imc1 .isVisible()){
      imc1 =new imc();
      jDesktopPane1.add(imc1 );
      imc1 .toFront();
      imc1 .setVisible(true);}
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
    if (!repor .isVisible()){
      repor =new reporteador();
      jDesktopPane1.add(repor );
      repor.toFront();
      repor .setVisible(true);}
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void menuentrenamiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuentrenamiento1ActionPerformed
        if (!entre2 .isVisible()){
      entre2 =new Entrenamiento2();
      jDesktopPane1.add(entre2 );
      entre2.toFront();
      entre2 .setVisible(true);}
    }//GEN-LAST:event_menuentrenamiento1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        if (!entrenador .isVisible()){
      entrenador =new Entrenador();
      jDesktopPane1.add(entrenador );
      entrenador.toFront();
      entrenador .setVisible(true);}
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try
        {
            UIManager.setLookAndFeel(new SyntheticaBlueMoonLookAndFeel());    
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error en en Look and Feel","Error",ERROR);
        }
        

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new miprincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel fechlabel;
    public static javax.swing.JLabel foto_label2;
    private javax.swing.JButton jButton5;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menucalendario;
    private javax.swing.JMenu menucontrol;
    public static javax.swing.JMenuItem menuentrenamiento;
    public static javax.swing.JMenuItem menuentrenamiento1;
    public static javax.swing.JLabel nombrePrincipal;
    private javax.swing.JLabel relolabel;
    // End of variables declaration//GEN-END:variables
}
