/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CargarEntrenamiento;

import CargarEntrenamiento.lstEntrenamiento;
import CargarEntrenamiento.lstFederados;
import conexionBase.conexionCargas;
import conexionBase.conexionEntrena;
import static entrenamiento.Entrenamiento.comboDias;
import static entrenamiento.Entrenamiento.comboSemana;
import static entrenamiento.Entrenamiento.valor;
import entrenamiento.grafica;
import entrenamiento.graficaEntrenamiento;
import force.miprincipal;
import java.awt.BorderLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author CarlosEfrain
 */
public class cargarEntreno extends javax.swing.JInternalFrame {
String [] columna ={"Fecha ","Peso"};
public static double[] valorentreno;
public static int dia, sema,contDias=0;
public static int diasmax=0;
public static int selecCargarEn=0;
public static DateFormat fecha = new SimpleDateFormat("yyyy/MM/dd");
public static Date fecha1,fechaGuar;
public static String codigoEntreno,fechaFormat;
conexionEntrena obj;
public static conexionCargas cargas;
public static DefaultTableModel modelo;

DecimalFormatSymbols simbolos = new DecimalFormatSymbols();
 
DecimalFormat formatter;
DecimalFormat formatter3;
DecimalFormat formatter2;

DefaultTableModel encabezado;
   
    /**
     * Creates new form cargarEntreno
     */
    public cargarEntreno() {
        initComponents();
        simbolos.setDecimalSeparator('.');
        formatter = new DecimalFormat("#0.00",simbolos); 
        formatter3 = new DecimalFormat("#0",simbolos); 
        formatter2 = new DecimalFormat("#0.5",simbolos); 
        encabezado=(DefaultTableModel)tbltablaCargar.getModel();
        
        
         tbltablaCargar.setModel(encabezado);
         cargas=new conexionCargas();
         lunes.setEnabled(false);
         martes.setEnabled(false);
         Miercoles.setEnabled(false);
        jueves.setEnabled(false);
        Viernes.setEnabled(false);
        sabado.setEnabled(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnFederado = new javax.swing.JButton();
        txtnombreEntreno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BTNentrenamiento = new javax.swing.JButton();
        txtnombrefederado1 = new javax.swing.JTextField();
        txtcodigofederado = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtsemana = new javax.swing.JTextField();
        txtdia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lunes = new javax.swing.JCheckBox();
        martes = new javax.swing.JCheckBox();
        Miercoles = new javax.swing.JCheckBox();
        jueves = new javax.swing.JCheckBox();
        Viernes = new javax.swing.JCheckBox();
        sabado = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltablaCargar = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtpeso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comborepeticion = new javax.swing.JComboBox();
        txtrm = new javax.swing.JTextField();
        btnrm = new javax.swing.JButton();
        fechaInic = new com.toedter.calendar.JDateChooser();
        imagen = new javax.swing.JLabel();
        btnrm1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("PLAN TREINO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/gym2.png"))); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CED. Deportista");

        btnFederado.setText("...");
        btnFederado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFederadoActionPerformed(evt);
            }
        });

        txtnombreEntreno.setEditable(false);
        txtnombreEntreno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnombreEntreno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreEntrenoKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Entrenamiento");

        BTNentrenamiento.setText("...");
        BTNentrenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNentrenamientoActionPerformed(evt);
            }
        });

        txtnombrefederado1.setEditable(false);
        txtnombrefederado1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnombrefederado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombrefederado1KeyTyped(evt);
            }
        });

        txtcodigofederado.setEditable(false);
        txtcodigofederado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcodigofederado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigofederadoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcodigofederado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtnombreEntreno)))
                    .addComponent(txtnombrefederado1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNentrenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFederado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodigofederado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFederado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombrefederado1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombreEntreno)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNentrenamiento))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Semanas de entreno");

        txtsemana.setEditable(false);
        txtsemana.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtdia.setEditable(false);
        txtdia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Dias de entreno");

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/our_process_2.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/graphics.stats-32.png"))); // NOI18N
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdia, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(txtsemana))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtsemana, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Días de entreno"));
        jPanel4.setToolTipText("Dias de entrenamiento");
        jPanel4.setName("Dias de entrenamiento"); // NOI18N

        lunes.setText("Lunes");
        lunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lunesActionPerformed(evt);
            }
        });

        martes.setText("Martes");
        martes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                martesActionPerformed(evt);
            }
        });

        Miercoles.setText("Miercoles");
        Miercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiercolesActionPerformed(evt);
            }
        });

        jueves.setText("Jueves");
        jueves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juevesActionPerformed(evt);
            }
        });

        Viernes.setText("Viernes ");
        Viernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViernesActionPerformed(evt);
            }
        });

        sabado.setText("sabados ");
        sabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sabado)
                    .addComponent(Viernes)
                    .addComponent(jueves)
                    .addComponent(Miercoles)
                    .addComponent(martes)
                    .addComponent(lunes))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lunes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(martes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Miercoles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jueves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Viernes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sabado)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tbltablaCargar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbltablaCargar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Peso", "Serie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbltablaCargar);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "1RM"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Peso KG");

        txtpeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpesoKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Repeticiones ");

        comborepeticion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comborepeticion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione repeticiones ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        comborepeticion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comborepeticionMouseClicked(evt);
            }
        });
        comborepeticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comborepeticionActionPerformed(evt);
            }
        });

        txtrm.setEditable(false);
        txtrm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnrm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/rm.png"))); // NOI18N
        btnrm.setText(">>");
        btnrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtrm, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnrm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comborepeticion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(3, 3, 3))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comborepeticion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrm))
                .addGap(4, 4, 4))
        );

        fechaInic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fechaInicFocusGained(evt);
            }
        });
        fechaInic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechaInicMouseClicked(evt);
            }
        });

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/profile-42914_640.png"))); // NOI18N

        btnrm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos_iconos/pesas.png"))); // NOI18N
        btnrm1.setText("!>");
        btnrm1.setAlignmentY(0.0F);
        btnrm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrm1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaInic, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnrm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnrm1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fechaInic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
cargar();   
universales();   
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void BTNentrenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNentrenamientoActionPerformed
  
   lstEntrenamiento  dialog2 = new lstEntrenamiento(new javax.swing.JFrame(), true);
   dialog2.setLocationRelativeTo(null);
   dialog2.setVisible(true);  
  universales();   
   // TODO add your handling code here:
    }//GEN-LAST:event_BTNentrenamientoActionPerformed

    private void btnFederadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFederadoActionPerformed
   lstFederados  federados = new lstFederados (new javax.swing.JFrame(), true);
   federados.setLocationRelativeTo(null);
   federados.setVisible(true);  
   universales();   // TODO add your handling code here:
    }//GEN-LAST:event_btnFederadoActionPerformed

    private void btnrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrmActionPerformed
    modelo=(DefaultTableModel) tbltablaCargar.getModel();
    tbltablaCargar.setModel(modelo);
        int filas= tbltablaCargar.getRowCount();
        // JOptionPane.showMessageDialog(null, filas);
  
   // 
     double porcentaje, rm; 
     String po;
     double peso; 
     rm=Double.parseDouble(txtrm.getText());
        for (int i = 0; i < filas; i++) {
            porcentaje=Double.parseDouble(modelo.getValueAt(i, 1).toString());
            peso=rm *(porcentaje/100);
             //modelo.addRow(columna);
            modelo.setValueAt(formatter3.format(peso), i, 1);
          }
    }//GEN-LAST:event_btnrmActionPerformed

    private void lunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lunesActionPerformed
        if(lunes.isSelected())contDias++;
        else contDias--;
         validarDias();
        // TODO add your handling code here:
    }//GEN-LAST:event_lunesActionPerformed

    private void martesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_martesActionPerformed
  if(martes.isSelected())contDias++;
        else contDias--;
         validarDias();        // TODO add your handling code here:
    }//GEN-LAST:event_martesActionPerformed

    private void MiercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiercolesActionPerformed
  if(Miercoles.isSelected())contDias++;
        else contDias--;
         validarDias();        // TODO add your handling code here:
    }//GEN-LAST:event_MiercolesActionPerformed

    private void juevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juevesActionPerformed
  if(jueves.isSelected())contDias++;
        else contDias--;
         validarDias();        // TODO add your handling code here:
    }//GEN-LAST:event_juevesActionPerformed

    private void ViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViernesActionPerformed
  if(Viernes.isSelected())contDias++;
        else contDias--;
         validarDias();        // TODO add your handling code here:
    }//GEN-LAST:event_ViernesActionPerformed

    private void sabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabadoActionPerformed
  if(sabado.isSelected())contDias++;
        else contDias--;
         validarDias();        // TODO add your handling code here:
    }//GEN-LAST:event_sabadoActionPerformed

    private void txtnombreEntrenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreEntrenoKeyTyped

       
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreEntrenoKeyTyped

    private void fechaInicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaInicMouseClicked
     // JOptionPane.showMessageDialog(null,"entroo :)");
        if(contDias==diasmax && fechaInic.getDate()!=null)cargar();
        universales();   
    }//GEN-LAST:event_fechaInicMouseClicked

    private void txtpesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesoKeyTyped
        try {
            Double.parseDouble(txtpeso.getText()+evt.getKeyChar());
            calcula1rm(txtpeso.getText()+evt.getKeyChar());
        } catch (Exception e) {
            calcula1rm(txtpeso.getText());
            evt.consume();
            
        }
        universales();   
               // TODO add your handling code here:
    }//GEN-LAST:event_txtpesoKeyTyped

    private void comborepeticionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comborepeticionMouseClicked
      // TODO add your handling code here:
    }//GEN-LAST:event_comborepeticionMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
if (tbltablaCargar.getRowCount()<1){
           JOptionPane.showMessageDialog(null," Error faltan parametros ","Error",JOptionPane.ERROR_MESSAGE);}
    //limpiarTabla(tbltabla);
else {
 int dt=0,mt=1;
 //migrafic.llenas1();
 //migrafic.borrars1();
 valorentreno=new double[tbltablaCargar.getRowCount()];
 for( int s=0;s < tbltablaCargar.getRowCount(); s++ ){   
     valorentreno[s]=Double.parseDouble(tbltablaCargar.getValueAt(s, 1).toString());
   }
  grafica2 migrafic=new grafica2();
  //migrafic.llenarXY(valor);
//migrafica gfica = new migrafica();
 //       miprincipal.jDesktopPane1.add(gfica);  
 //       gfica.show();
  graficaEntrenamiento2  dialog32 = new graficaEntrenamiento2(new javax.swing.JFrame(), true);
  dialog32.setLocationRelativeTo(null);
  dialog32.setVisible(true);}
universales();   
// TODO add your handling code here:
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        miprincipal.planprin=true;
     miprincipal.calendarioprin=false;
     miprincipal.entrenamiento=false;
      miprincipal.usuario=false;
     miprincipal.federado=false;
    }//GEN-LAST:event_formMouseClicked

    private void txtcodigofederadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigofederadoKeyTyped
universales();        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigofederadoKeyTyped

    private void txtnombrefederado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrefederado1KeyTyped
universales();           // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrefederado1KeyTyped

    private void comborepeticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comborepeticionActionPerformed
       calcula1rm(txtpeso.getText());  
    }//GEN-LAST:event_comborepeticionActionPerformed

    private void btnrm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrm1ActionPerformed
    modelo=(DefaultTableModel) tbltablaCargar.getModel();
    tbltablaCargar.setModel(modelo);
     int filas= tbltablaCargar.getRowCount();
        // JOptionPane.showMessageDialog(null, filas);
  
   // 
     double p, rm; 
     String po;
     double peso; 
     boolean seguir=true;
     double valorPesoReal=20;
     rm=Double.parseDouble(txtrm.getText());
        for (int i = 0; i < filas; i++) {
            valorPesoReal=20;
            p=Double.parseDouble(modelo.getValueAt(i, 1).toString());
            while(p>valorPesoReal){
                valorPesoReal=valorPesoReal+2.5;
               }
            if (p!=valorPesoReal)
            valorPesoReal=valorPesoReal-2.5;
          //  JOptionPane.showMessageDialog(null, p);
             //modelo.addRow(columna);
            modelo.setValueAt(formatter.format(valorPesoReal), i, 1); }
    }//GEN-LAST:event_btnrm1ActionPerformed

    private void fechaInicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaInicFocusGained
      // JOptionPane.showMessageDialog(null, "esta cambiando");
    }//GEN-LAST:event_fechaInicFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNentrenamiento;
    public static javax.swing.JCheckBox Miercoles;
    public static javax.swing.JCheckBox Viernes;
    private javax.swing.JButton btnFederado;
    private javax.swing.JButton btnrm;
    private javax.swing.JButton btnrm1;
    public static javax.swing.JComboBox comborepeticion;
    public static com.toedter.calendar.JDateChooser fechaInic;
    public static javax.swing.JLabel imagen;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JCheckBox jueves;
    public static javax.swing.JCheckBox lunes;
    public static javax.swing.JCheckBox martes;
    public static javax.swing.JCheckBox sabado;
    public static javax.swing.JTable tbltablaCargar;
    public static javax.swing.JTextField txtcodigofederado;
    public static javax.swing.JTextField txtdia;
    public static javax.swing.JTextField txtnombreEntreno;
    public static javax.swing.JTextField txtnombrefederado1;
    public static javax.swing.JTextField txtpeso;
    public static javax.swing.JTextField txtrm;
    public static javax.swing.JTextField txtsemana;
    // End of variables declaration//GEN-END:variables
public String hola(){
return "hola";}


public void setCodigoEntreno(String c){
    codigoEntreno=c;
}
public String getCodigoEntreno(){
    return codigoEntreno;
}
public int getselecCargarEn(){
    return selecCargarEn;
}
public void validarDias(){


if(contDias==diasmax){
  //  JOptionPane.showMessageDialog(null, "ejecu");
    if(!lunes.isSelected())lunes.setEnabled(false);
    if(!martes.isSelected())martes.setEnabled(false);
    if(!Miercoles.isSelected())Miercoles.setEnabled(false);
    if(!jueves.isSelected())jueves.setEnabled(false);
    if(!Viernes.isSelected())Viernes.setEnabled(false);
    if(!sabado.isSelected())sabado.setEnabled(false);
    if(fechaInic.getDate()!=null)cargar();
}
else {
    // JOptionPane.showMessageDialog(null, "activo");
    if(!lunes.isSelected())lunes.setEnabled(true);
    if(!martes.isSelected())martes.setEnabled(true);
    if(!Miercoles.isSelected())Miercoles.setEnabled(true);
    if(!jueves.isSelected())jueves.setEnabled(true);
    if(!Viernes.isSelected())Viernes.setEnabled(true);
    if(!sabado.isSelected())sabado.setEnabled(true);
}
universales();   
}
public static boolean todolleno(){
if(String.valueOf(selecCargarEn).equals("")||txtcodigofederado.getText().equals("")||fechaInic.getDate()==null|| diasmax!=contDias)
    return false;
else  
      return true;
}
public static void ingresarCargas(){
    //String fch,  String peso,  String idEnt, String idFede
     cargas=new conexionCargas();
       int filas;
       fechaGuar = fechaInic.getDate();
       fechaFormat=fecha.format(fechaGuar);
     //  JOptionPane.showMessageDialog(null, "codigo federado: "+txtcodigofederado.getText());
       if(modelo==null)JOptionPane.showMessageDialog(null, "No a seleccionado la 1RM");
       filas=modelo.getRowCount();
      cargas.consulfehaDisponible(txtcodigofederado.getText(), String.valueOf(selecCargarEn));
      try {
          //////////////////// en caso de que la fecha sea null
        if(conexionCargas.fecha!=null){
       if(fecha.parse((String.valueOf(modelo.getValueAt(0,0)))).before(fecha.parse(conexionCargas.fecha)))
           JOptionPane.showMessageDialog(null, "LA Fecha de Inicio debe ser mayor a: "+conexionCargas.fecha); 
        else {try {
         for (int i = 0; i < filas; i++) {
               cargas.ingresarCrgas( String.valueOf(modelo.getValueAt(i,0)), String.valueOf(modelo.getValueAt(i,1)),String.valueOf(selecCargarEn),txtcodigofederado.getText(),String.valueOf(modelo.getValueAt(i,2))); }
         
         JOptionPane.showMessageDialog(null, "datos ingresados correctamente");
         nuevo();
      } 
      catch (Exception e) {
    }}
       ////////////////////////////////////////////////7
        }// if null
       
        else if (conexionCargas.fecha==null) {try {
         for (int i = 0; i < filas; i++) {
               cargas.ingresarCrgas( String.valueOf(modelo.getValueAt(i,0)), String.valueOf(modelo.getValueAt(i,1)),String.valueOf(selecCargarEn),txtcodigofederado.getText(),String.valueOf(modelo.getValueAt(i,2))); }
         
         JOptionPane.showMessageDialog(null, "datos ingresados correctamente");
         nuevo();
      } 
      catch (Exception e) {
    }}
        ////////////////////// la fecha fue nula no encontro nada 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "hay un erro:"+e.getMessage());
    }
       }
public void cargar(){
   obj = new conexionEntrena();
      String identreno;
      fecha1 = fechaInic.getDate();
    identreno = String.valueOf( selecCargarEn);
    // selecciono lunes y miercoles
      obj.consultarplantotal(fecha1, identreno, tbltablaCargar, lunes.isSelected(),martes.isSelected(), Miercoles.isSelected(), jueves.isSelected(), Viernes.isSelected(), sabado.isSelected());}
public void calcula1rm(String peso1){
    if(peso1.equals(""))peso1="0";
if ( comborepeticion.getSelectedIndex()>0){
double peso=((Double.parseDouble(peso1)) / ( 1.0278 - ( 0.0278 * Double.parseDouble(comborepeticion.getSelectedItem().toString()) )));
txtrm.setText(String.valueOf(formatter.format(peso)));


}
        
}

public static void guardarPlanEntreno(){
 if (todolleno()) {
      //JOptionPane.showMessageDialog(null, "entro a guardar "); 
    ingresarCargas();
 }  
  else JOptionPane.showMessageDialog(null, "Faltan parametros a Ingresar","Error",JOptionPane.ERROR_MESSAGE);
    }    
public static void nuevo(){
    txtcodigofederado.setText("");
    txtnombrefederado1.setText("");
    txtnombreEntreno.setText("");
    txtpeso.setText("");
    comborepeticion.setSelectedIndex(0);
    txtrm.setText("");
    fechaInic.setCalendar(null);
    txtsemana.setText("");
    txtdia.setText("");
    lunes.setSelected(false);
    martes.setSelected(false);
    Miercoles.setSelected(false);
    jueves.setSelected(false);
    Viernes.setSelected(false);
    sabado.setSelected(false);
    lunes.setEnabled(false);
    martes.setEnabled(false);
    Miercoles.setEnabled(false);
    jueves.setEnabled(false);
    Viernes.setEnabled(false);
    sabado.setEnabled(false);
    limpiarTabla(tbltablaCargar);
    diasmax=0;
    String template = System.getProperty("user.dir");
    String path = template+"/src/recursos_iconos/profile-42914_640.png";
    imagen.setIcon( new ImageIcon(path));
}
public static void limpiarTabla(JTable tabla){
        try {
            modelo=(DefaultTableModel) tabla.getModel();
            int filas=tabla.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }
public void universales(){
     miprincipal.planprin=true;
     miprincipal.calendarioprin=false;
     miprincipal.entrenamiento=false;
     miprincipal.entrenamiento2=false;
     miprincipal.entrenadorr=false;
     miprincipal.usuario=false;
     miprincipal.federado=false; }
      
    
}
